backend:
  name: git-gateway
  branch: main 
media_folder: "src/admin/assets"
public_folder: "/src/assets/episodes"
publish_mode: editorial_workflow
drafts_enabled: true
site_url: https://karalorynlilly.com/
display_url: https://karalorynlilly.com/
logo_url: https://karalorynlilly.com/assets/logo/KLP_Submark_Forest.png
collections:
  - name: "episode" # Collection name, matching your Eleventy collection tag
    label: "Episodes" # Display name in CMS
    folder: "src/episodes" # Directory for episode files (create this if it doesn’t exist)
    create: true # Allow creating new episodes
    slug: "{{slug}}" # Generate URL-friendly slugs from titles
    preview_path: episodes/{{slug}} # Preview URL of the episode
    fields: # Fields matching your front matter
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Host", name: "host", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true, format: "YYYY-MM-DD" }
      - { label: "Intro Text", name: "description", widget: "text", required: true, maxlength: "160", hint: "This is used for meta descriptions and intro text on recent episode cards." }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Cover Art", name: "image", widget: "image", choose_url: false, hint: "Max file upload size is 1MB", media_library: { max_file_size: 1048576 } } # 1MB max for images
      - { label: "Duration", name: "duration", widget: "string", required: true, hint: "Format: HH:MM:SS or MM:SS (e.g., 00:11:20)" }
      - { label: "Episode Number", name: "episodeNumber", widget: "number", required: true, hint: "Enter  episode number; will display as 01, 02, 03, etc. on website." }
      - { label: "Audio Player", name: "audioEmbed", widget: "text", required: false, hint: "Paste the iframe embed code for the episode (e.g., from Apple Podcasts, Spotify, or YouTube)." }
      - { label: "Spotify URL", name: "spotify", widget: "string" }
      - { label: "YouTube URL", name: "youtube", widget: "string" }
      - { label: "Apple Podcasts URL", name: "apple", widget: "string" } 
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        default: ["episode"]
        allow_add: true
        field:
          label: "Tag"
          name: "tag"
          widget: "select"
          options:
            - family
            - faith
            - relationships
            - grace